name: run_retrospective_step
description: A subworkflow for running one iteration of a retrospective active learning simulation
keywords:
  - active_learning

components:
  - batchie/advance_retrospective_simulation
  - batchie/calculate_distance_metric_chunk
  - batchie/calculate_score_chunk
  - batchie/select_next_plate
  - batchie/train_model
  - batchie/evaluate_model

input:
  - ch_input:
      description: |
        An input channel containing experiment and up-to-date series of batch selections and losses
        Structure: [ val(meta), path(masked_experiment), path(unmasked_experiment), val(n_chains), val(n_chunks) ]

output:
  - ch_output:
      description: |
        The screen file with the next plate revealed
        Structure: [ val(meta), path(masked_experiment) ]
authors:
  - "@jeffquinn-msk"
