name: calculate_distance_matrix_chunk
description: Calculate one chunk of the pairwise distance matrix.
keywords:
  - active_learning
tools:
  - calculate_distance_matrix:
      description: |
        Calculate one chunk of the pairwise distance matrix.
      homepage: https://batchie.readthedocs.io/en/latest/command_line_interface.html#train-model
      documentation: https://batchie.readthedocs.io/en/latest/command_line_interface.html#train-model
      licence: []
      args_id: "$args"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - data:
      type: file
      description: |
        Batchie experiment file (.h5) as documented at
        https://batchie.readthedocs.io/en/latest/data_format.html#experiment-format
  - thetas:
      type: file
      description: |
        h5 file containing trained model parameters (.h5)
  - chunk_index:
      type: integer
      description: Index of the current chunk being calculated
  - n_chunks:
      type: integer
      description: Number of chunks in the total distance matrix

output:
  - distance_matrix_chunk:
      type: file
      description: h5 file containing the distance matrix chunk
      pattern: "distance_matrix_chunk.h5"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@jeffquinn-msk"
